//获取设备状态
export const GET_DEVICESINFO = 'GET_DEVICESINFO';
export const SET_TIMEPOPUP ="SET_TIMEPOPUP";
export const SET_PLAYDATA ="SET_PLAYDATA";
export const GET_LOCALLIST="GET_LOCALLIST";
export const PUT_LOCALLIST ="PUT_LOCALLIST";