//获取设备状态
export const GET_DEVICESINFO = 'GET_DEVICESINFO';
export const SET_TIMEPOPUP ="SET_TIMEPOPUP";
export const SET_PLAYDATA ="SET_PLAYDATA";
export const GET_LOCALLIST="GET_LOCALLIST";
export const PUT_LOCALLIST ="PUT_LOCALLIST";
export const SET_MUSICDATA ="SET_MUSICDATA";
export const SET_PLAYMODE ="SET_PLAYMODE";
export const SET_SRSULTSTRALL ="SET_SRSULTSTRALL";
export const SETLOCALCID ="SETLOCALCID";
export const LOADINGFLAG ="LOADINGFLAG";
export const ENGLISHDATA ='ENGLISHDATA';
export const SET_UPFLAG ="SET_UPFLAG"